import type { Run, Step, Warning } from '../model.js';
import { verifyRun } from '../integrity/verify.js';

/**
 * Render a standalone, self-contained HTML audit report for a run (PRD §M3).
 * No external assets — this single file is the artifact handed to an auditor.
 */
export function renderReport(run: Run): string {
  const verify = verifyRun(run);
  const fmtCost = (n: number) => `${run.currency} ${n.toFixed(2)}`;

  const badge = verify.ok
    ? `<span class="badge ok">&#10003; Integrity verified &middot; chain intact</span>`
    : `<span class="badge bad">&#10007; Integrity FAILED &middot; ${esc(verify.message)}</span>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>traceglass audit report &middot; ${esc(run.name)}</title>
<style>${STYLES}</style>
</head>
<body>
<header>
  <div class="brand">traceglass <span class="tag">audit report</span></div>
  ${badge}
</header>

<section class="summary">
  <h1>${esc(run.name)}</h1>
  <table class="kv">
    <tr><th>Run id</th><td class="mono">${esc(run.id)}</td></tr>
    <tr><th>Status</th><td>${esc(run.status)}</td></tr>
    <tr><th>Started</th><td class="mono">${esc(run.startedAt)}</td></tr>
    <tr><th>Ended</th><td class="mono">${esc(run.endedAt)}</td></tr>
    <tr><th>Steps</th><td>${run.totals.steps}</td></tr>
    <tr><th>Tokens</th><td>${run.totals.tokens.toLocaleString()}</td></tr>
    <tr><th>Cost</th><td>${fmtCost(run.totals.cost)}</td></tr>
    <tr><th>Duration</th><td>${run.totals.durationMs.toLocaleString()} ms</td></tr>
    <tr><th>Integrity anchor (runHash)</th><td class="mono break">${esc(run.runHash)}</td></tr>
  </table>
</section>

${renderWarnings(run.warnings)}

<section>
  <h2>Steps</h2>
  <table class="steps">
    <thead>
      <tr><th>#</th><th>Type</th><th>Label</th><th>Tool</th><th>Tokens</th><th>Cost</th><th>Data read / mutated</th><th>Hash</th></tr>
    </thead>
    <tbody>
      ${run.steps.map((s) => renderStepRow(s, run.currency)).join('\n')}
    </tbody>
  </table>
</section>

<footer>
  Generated by traceglass &middot; tamper-evident audit record &middot; verify with
  <span class="mono">traceglass verify ${esc(run.id)}</span>
</footer>
</body>
</html>`;
}

function renderWarnings(warnings: Warning[]): string {
  if (warnings.length === 0) {
    return `<section><h2>Warnings</h2><p class="muted">None.</p></section>`;
  }
  return `<section>
  <h2>Warnings (${warnings.length})</h2>
  <ul class="warnings">
    ${warnings
      .map(
        (w) =>
          `<li class="w-${esc(w.kind)}"><span class="wkind">${esc(w.kind)}</span> ${esc(w.message)}</li>`,
      )
      .join('\n')}
  </ul>
</section>`;
}

function renderStepRow(s: Step, currency: string): string {
  return `<tr class="t-${esc(s.type)}">
  <td class="mono">${s.index}</td>
  <td>${esc(s.type)}</td>
  <td>${esc(s.label)}</td>
  <td>${esc(s.toolName ?? '')}</td>
  <td class="mono num">${s.tokens || ''}</td>
  <td class="mono num">${s.cost ? `${currency} ${s.cost.toFixed(2)}` : ''}</td>
  <td><pre class="payload">${esc(payload(s.dataPayload))}</pre></td>
  <td class="mono hash" title="${esc(s.hash)}">${esc(s.hash.slice(0, 12))}&hellip;</td>
</tr>`;
}

function payload(value: unknown): string {
  if (value === undefined) return '';
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}

/**
 * HTML-escape AND fold every non-ASCII codepoint to a numeric entity, so the
 * report is pure ASCII. An audit artifact gets opened in unpredictable places
 * (email, a Latin-1 viewer, copy-paste) where a stray `<meta charset>` may be
 * ignored; pure ASCII renders identically everywhere and avoids mojibake.
 */
function esc(value: string): string {
  let out = '';
  for (const ch of value) {
    const cp = ch.codePointAt(0)!;
    if (ch === '&') out += '&amp;';
    else if (ch === '<') out += '&lt;';
    else if (ch === '>') out += '&gt;';
    else if (ch === '"') out += '&quot;';
    else if (cp > 0x7e || (cp < 0x20 && ch !== '\n' && ch !== '\t')) out += `&#${cp};`;
    else out += ch;
  }
  return out;
}

const STYLES = `
:root{--bg:#0b0f17;--panel:#121826;--line:#1f2937;--fg:#e5e7eb;--muted:#94a3b8;--accent:#7c5cff;--amber:#f59e0b;--red:#ef4444;--green:#22c55e;}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:0 0 64px}
.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
.break{word-break:break-all}.num{text-align:right}
header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 28px;border-bottom:1px solid var(--line);position:sticky;top:0;background:var(--bg)}
.brand{font-weight:700;font-size:18px;letter-spacing:.5px}
.tag{font-weight:500;font-size:11px;color:var(--muted);border:1px solid var(--line);border-radius:6px;padding:2px 8px;margin-left:8px;text-transform:uppercase}
.badge{font-size:13px;font-weight:600;padding:6px 12px;border-radius:8px}
.badge.ok{color:var(--green);background:rgba(34,197,94,.12);border:1px solid rgba(34,197,94,.4)}
.badge.bad{color:var(--red);background:rgba(239,68,68,.12);border:1px solid rgba(239,68,68,.4)}
section{padding:20px 28px;border-bottom:1px solid var(--line)}
h1{font-size:20px;margin:0 0 14px}h2{font-size:15px;text-transform:uppercase;letter-spacing:.6px;color:var(--muted);margin:0 0 12px}
table{border-collapse:collapse;width:100%}
.kv{max-width:720px}.kv th{text-align:left;color:var(--muted);font-weight:500;padding:4px 16px 4px 0;white-space:nowrap;vertical-align:top}.kv td{padding:4px 0}
.steps{font-size:13px}.steps th{text-align:left;color:var(--muted);font-weight:600;border-bottom:1px solid var(--line);padding:8px 10px}
.steps td{border-bottom:1px solid var(--line);padding:8px 10px;vertical-align:top}
.payload{margin:0;max-width:340px;max-height:160px;overflow:auto;white-space:pre-wrap;word-break:break-word;color:var(--accent);font-family:ui-monospace,Menlo,monospace;font-size:12px}
.hash{color:var(--muted)}
tr.t-error td{background:rgba(239,68,68,.06)}
.warnings{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:8px}
.warnings li{padding:10px 12px;border-radius:8px;border:1px solid var(--line);background:var(--panel)}
.warnings .w-loop{border-color:rgba(245,158,11,.5)}.warnings .w-high_cost_step{border-color:rgba(245,158,11,.5)}.warnings .w-error{border-color:rgba(239,68,68,.5)}
.wkind{display:inline-block;font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:var(--amber);margin-right:8px;font-weight:700}
.w-error .wkind{color:var(--red)}
.muted{color:var(--muted)}
footer{padding:18px 28px;color:var(--muted);font-size:12px}
`;
