import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parseEvidence } from '../evidence.js';
import { verifyRun } from './verify.js';
import { verifyRunFull } from './signing.js';
import { hashStep, canonicalStep, applyHashChain, computeRunHash } from './hash.js';
import { redactRun } from '../redact/redact.js';

/**
 * THE COMPATIBILITY INVARIANT.
 *
 * Every record published between 0.3.0 and 0.8.0 is `tgcanon/1` and carries no
 * `hashVersion`. Those files are in auditors' hands, in WORM buckets, attached
 * to incident reports. The entire product promise is that an evidence file
 * stays verifiable — so introducing version 2 is only legitimate if version 1
 * keeps verifying, bit for bit, forever.
 *
 * This file is the standing proof. The fixtures it reads are:
 *
 *   - `docs/test-vectors/04-runs/*.tgev.json` — the frozen conformance corpus,
 *     generated from the shipped implementation and re-derived independently by
 *     `docs/test-vectors/check.mjs`;
 *   - `legacy-signed` / `legacy-redacted` — produced by the PRE-CHANGE build,
 *     immediately before version 2 was written, and committed unmodified.
 *
 * If any assertion here fails, the change that caused it broke published
 * evidence and must not ship, whatever else is green.
 */

const vectorsDir = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../../../docs/test-vectors/04-runs',
);
const loadRun = (name: string) =>
  parseEvidence(JSON.parse(readFileSync(join(vectorsDir, `${name}.tgev.json`), 'utf8')));

/** The frozen corpus, plus the two records generated by the pre-change build. */
const LEGACY = ['minimal', 'committed', 'redacted', 'signed', 'legacy-signed', 'legacy-redacted'];

describe('published tgcanon/1 records still verify', () => {
  for (const name of LEGACY) {
    it(`${name}.tgev.json verifies clean`, () => {
      const run = loadRun(name);
      // These records predate the version field. Their version is the ABSENCE
      // of it, and nothing may fill it in retroactively.
      expect(run.hashVersion).toBeUndefined();

      const result = verifyRunFull(run);
      expect(result.chain.ok).toBe(true);
      expect(result.chain.hashVersion).toBe(1);
      expect(result.signature.ok).toBe(true);
      expect(result.ok).toBe(true);
    });
  }

  it('their anchors are unchanged — v1 still anchors on the final step hash', () => {
    for (const name of LEGACY) {
      const run = loadRun(name);
      if (run.steps.length === 0) continue;
      expect([name, run.runHash]).toEqual([name, run.steps[run.steps.length - 1]!.hash]);
      expect([name, computeRunHash(run)]).toEqual([name, run.runHash]);
    }
  });

  it('their step hashes recompute to the same bytes under the v1 path', () => {
    for (const name of LEGACY) {
      let prev = '';
      for (const step of loadRun(name).steps) {
        expect([name, step.id, hashStep(step, prev, 1)]).toEqual([name, step.id, step.hash]);
        // The canonical form itself, not just the digest — the thing an
        // independent verifier in another language has to reproduce.
        expect(canonicalStep(step, 1)).toBe(canonicalStep(step));
        prev = step.hash;
      }
    }
  });

  it('the commitment-based redaction property still holds on the frozen corpus', () => {
    // `committed` and `redacted` differ in payload but share an anchor. This is
    // the defining property of the format and the vectors pin it.
    expect(loadRun('redacted').runHash).toBe(loadRun('committed').runHash);
    expect(loadRun('legacy-redacted').runHash).toBe(loadRun('legacy-signed').runHash);
  });

  it('a legacy record re-chained by this build stays version 1', () => {
    // `applyHashChain` defaults to the current version for NEW captures, but a
    // record that already declares (or implies) a version keeps it. Silently
    // upgrading a legacy record would change its anchor and orphan every copy
    // an auditor already holds.
    const run = loadRun('legacy-signed');
    const rechained = applyHashChain(run);
    expect(rechained.hashVersion).toBeUndefined();
    expect(rechained.runHash).toBe(run.runHash);
    expect(rechained.steps.map((s) => s.hash)).toEqual(run.steps.map((s) => s.hash));
  });

  it('redacting a legacy record still uses v1 paths and preserves its anchor', () => {
    const run = loadRun('legacy-signed');
    const { run: redacted, redacted: paths } = redactRun(run, { paths: ['input.account'] });
    expect(paths.length).toBeGreaterThan(0);
    expect(redacted.runHash).toBe(run.runHash);
    expect(verifyRunFull(redacted).ok).toBe(true);
    expect(JSON.stringify(redacted)).not.toContain('4471');
  });

  it('legacy records keep their known weaknesses — v1 rules are not "improved"', () => {
    // The temptation on a change like this is to retrofit the new checks onto
    // old records. That would change the verdict on files already issued, which
    // is its own kind of dishonesty: a record that verified yesterday must
    // verify today. The v1 holes stay open, and the spec says so.
    const run = loadRun('legacy-signed');
    expect(verifyRun({ ...run, currency: 'USD' }).ok).toBe(true);
    expect(verifyRun({ ...run, status: 'failed' }).ok).toBe(true);
  });
});
